//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentWeek9.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string username { get; set; }
        public string address { get; set; }
        public int postalCode { get; set; }
        public string city { get; set; }
        public string password { get; set; }
    }
}
